var colorsArray = {
    "colors":[
        {
            "name":"green",
            "red":"64",
            "green":"175",
            "blue":"63",
        },
        {
            "name":"yellow",
            "red":"239",
            "green":"183",
            "blue":"62"
        },
        {
            "name":"red",
            "red":"192",
            "green":"46",
            "blue":"35"
        },
        {
            "name":"blue",
            "red":"19",
            "green":"71",
            "blue":"144",
        },
        {
            "name":"orange",
            "red":"253",
            "green":"92",
            "blue":"48"
        },
    ]
};